const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.advert,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Behaviors.MoveTo,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Behaviors.Car,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.EightDir.Acts.SetIgnoreInput,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SetLayoutEffectParam,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Particles.Acts.SetEffectParam,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.advert.Acts.ShowInterstitial,
		C3.Plugins.advert.Acts.CreateInterstitial,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.advert.Acts.CreateRewardedInterstitial,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Rotate: 0},
	{chas: 0},
	{var: 0},
	{clock: 0},
	{Fade: 0},
	{clock2: 0},
	{marker: 0},
	{second: 0},
	{second2: 0},
	{markerCollision: 0},
	{minutes: 0},
	{Anchor: 0},
	{bestScoteText: 0},
	{coinsText: 0},
	{version: 0},
	{ConstText: 0},
	{lastScore: 0},
	{score: 0},
	{Sprite: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{MobileAdvert: 0},
	{Touch: 0},
	{Browser: 0},
	{line: 0},
	{play: 0},
	{MoveTo: 0},
	{namegame: 0},
	{TiledBackground: 0},
	{coinIcon: 0},
	{ScrollTo: 0},
	{camera: 0},
	{ThemeParam: 0},
	{icons8_sun_480px: 0},
	{markerCollision2: 0},
	{perfect: 0},
	{"8Direction": 0},
	{coin: 0},
	{Particles: 0},
	{instructions: 0},
	{dificult_text: 0},
	{leftArrow: 0},
	{rightArrow: 0},
	{Display: 0},
	{resumeBox: 0},
	{continue: 0},
	{noSanks: 0},
	{Sine: 0},
	{Sine2: 0},
	{sosiskaFanny: 0},
	{cloud: 0},
	{sosiskaSad: 0},
	{Car: 0},
	{block: 0},
	{block2: 0},
	{main: 0},
	{Pin: 0},
	{relive: 0},
	{speed: 0},
	{skin: 0},
	{ads: 0},
	{theme: 0},
	{textTrol: 0},
	{ratePrefect: 0},
	{game: 0},
	{resumeVar: 0},
	{bestScoreEasy: 0},
	{bestScoreHard: 0},
	{bestScoreExpert: 0},
	{coins: 0}
];

self.InstanceType = {
	chas: class extends self.ISpriteInstance {},
	clock: class extends self.ISpriteInstance {},
	clock2: class extends self.ISpriteInstance {},
	marker: class extends self.ISpriteInstance {},
	second: class extends self.ISpriteInstance {},
	second2: class extends self.ISpriteInstance {},
	markerCollision: class extends self.ISpriteInstance {},
	minutes: class extends self.ISpriteInstance {},
	bestScoteText: class extends self.ISpriteFontInstance {},
	coinsText: class extends self.ISpriteFontInstance {},
	ConstText: class extends self.ISpriteFontInstance {},
	lastScore: class extends self.ISpriteFontInstance {},
	score: class extends self.ISpriteFontInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	MobileAdvert: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	line: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	namegame: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	coinIcon: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	ThemeParam: class extends self.ISpriteInstance {},
	icons8_sun_480px: class extends self.ISpriteInstance {},
	markerCollision2: class extends self.ISpriteInstance {},
	perfect: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	instructions: class extends self.ISpriteInstance {},
	dificult_text: class extends self.ISpriteInstance {},
	leftArrow: class extends self.ISpriteInstance {},
	rightArrow: class extends self.ISpriteInstance {},
	Display: class extends self.ISpriteInstance {},
	resumeBox: class extends self.ISpriteInstance {},
	continue: class extends self.ISpriteInstance {},
	noSanks: class extends self.ISpriteInstance {},
	sosiskaFanny: class extends self.ISpriteInstance {},
	cloud: class extends self.ISpriteInstance {},
	sosiskaSad: class extends self.ISpriteInstance {},
	block: class extends self.ISpriteInstance {},
	block2: class extends self.ISpriteInstance {},
	main: class extends self.ISpriteInstance {},
	relive: class extends self.ISpriteInstance {}
}